<?php

namespace AppBundle\Core\Service;

/**
 * PostingCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostingCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
