<?php

namespace AppBundle\Core\Service;

/**
 * SocialProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
